//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 1.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_My1TYPE                     129
#define ID_IMAGEPROCESSING_OPENBMPFILE  32771
#define ID_IMAGEPROCESSING_DISPLAYFILEHEADER 32772
#define ID_IMAGEPROCESSING_READPIXELVALUE 32773
#define ID_IMAGEPROCESSING_SETPIXELVALUE 32774
#define ID_IMAGEPROCESSING_SAVETONEWBMPFILE 32775
#define ID_IMAGEPROCESSING_IMAGEINTERPOLATION 32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
